name: Merge

on:
  push:
    branches:
      - main

jobs:
  deploy_flatpak:
    name: Deploy Flatpak (${{ matrix.configuration.arch }})
    runs-on: ${{ matrix.configuration.runs-on }}

    strategy:
      matrix:
        configuration:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8-${{ matrix.configuration.arch }}
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.5
        with:
          bundle: tasks.flatpak
          manifest-path: io.elementary.tasks.json
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
          branch: daily
          arch: ${{ matrix.configuration.arch }}

      - name: Deploy
        uses: flatpak/flatpak-github-actions/flat-manager@v6.5
        with:
          repository: appcenter
          flat-manager-url: https://flatpak-api.elementary.io
          token: ${{ secrets.FLAT_MANAGER_TOKEN }}

  gettext:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Update Translation Files
      uses: elementary/actions/gettext-template@main
      env:
        GIT_USER_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
        GIT_USER_NAME: "elementaryBot"
        GIT_USER_EMAIL: "builds@elementary.io"
